-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.791.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 14-Jun-22 03:55:01
-- Target server version: 8.0.28
-- Please backup your target database before running this script 

CREATE DATABASE IF NOT EXISTS backendposdata COLLATE utf8mb4_0900_ai_ci;
USE backendposdata;

# .\PreDeployment.sql

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
# .\Tables\ss_tsaccount.Tables.sql
CREATE TABLE ss_tsaccount (
  AID BINARY(16) NOT NULL DEFAULT '' COMMENT 'UUID PK',
  Username VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'User',
  Password VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Password',
  PRIMARY KEY (AID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_as_ci;


# .\PostDeployment.sql

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;